### ISSUE TITLE
Worker errors in a weird way

### ISSUE THREAD

**Issue by sadovnik** [sadovnik/reader#37]
```
15:25:02 worker.1 | rake aborted!
15:25:02 worker.1 | ActiveRecord::StatementInvalid: SQLite3::ReadOnlyException: attempt to write a readonly database: INSERT INTO "posts" ("internal_id", "title", "summary", "url", "source_id", "published_at", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)
15:25:02 worker.1 | /Users/cyril/projects/reader/app/services/post_builder.rb:16:in `build'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:16:in `block (2 levels) in perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:15:in `map'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:15:in `block in perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:6:in `reduce'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:6:in `perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:13:in `block (2 levels) in <top (required)>'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:10:in `loop'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:10:in `block in <top (required)>'
15:25:02 worker.1 | SQLite3::ReadOnlyException: attempt to write a readonly database
15:25:02 worker.1 | /Users/cyril/projects/reader/app/services/post_builder.rb:16:in `build'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:16:in `block (2 levels) in perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:15:in `map'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:15:in `block in perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:6:in `reduce'
15:25:02 worker.1 | /Users/cyril/projects/reader/app/workers/update_sources_worker.rb:6:in `perform'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:13:in `block (2 levels) in <top (required)>'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:10:in `loop'
15:25:02 worker.1 | /Users/cyril/projects/reader/lib/tasks/worker.rake:10:in `block in <top (required)>'
15:25:02 worker.1 | Tasks: TOP => worker
15:25:02 worker.1 | (See full trace by running task with --trace)
```

**Comment by sadovnik** [comment]
Can't reproduce.
